const mongoose = require('mongoose');

const timelineEventSchema = new mongoose.Schema(
  {
    topicId: { type: mongoose.Schema.Types.ObjectId, ref: 'Topic', required: true, index: true },
    // Stable id within the timeline generated by the AI.
    eventId: { type: String, required: true, index: true },

    date: { type: Date, default: null },
    rawDate: { type: String, default: '' }, // for "YYYY-MM" fallback
    title: { type: String, default: '' },
    whatHappened: { type: String, default: '' },
    whyItMatters: { type: String, default: '' },
    aiExplanation: { type: String, default: '' },

    // Optional link back to sources used to craft the event.
    sourceIds: { type: [String], default: [] },

    order: { type: Number, default: 0 },
  },
  { timestamps: true }
);

timelineEventSchema.index({ topicId: 1, eventId: 1 }, { unique: true });

module.exports = mongoose.model('TimelineEvent', timelineEventSchema);

